# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Lab\IMU recv\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 685)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 1091, 641))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gpb_Display = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpb_Display.sizePolicy().hasHeightForWidth())
        self.gpb_Display.setSizePolicy(sizePolicy)
        self.gpb_Display.setObjectName("gpb_Display")
        self.horizontalLayout.addWidget(self.gpb_Display)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gpb_Connection = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gpb_Connection.sizePolicy().hasHeightForWidth())
        self.gpb_Connection.setSizePolicy(sizePolicy)
        self.gpb_Connection.setObjectName("gpb_Connection")
        self.texbConStatus = QtWidgets.QTextBrowser(self.gpb_Connection)
        self.texbConStatus.setGeometry(QtCore.QRect(10, 20, 391, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texbConStatus.sizePolicy().hasHeightForWidth())
        self.texbConStatus.setSizePolicy(sizePolicy)
        self.texbConStatus.setObjectName("texbConStatus")
        self.verticalLayout.addWidget(self.gpb_Connection)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnCon = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCon.sizePolicy().hasHeightForWidth())
        self.btnCon.setSizePolicy(sizePolicy)
        self.btnCon.setCheckable(True)
        self.btnCon.setDefault(False)
        self.btnCon.setObjectName("btnCon")
        self.horizontalLayout_3.addWidget(self.btnCon)
        self.btnCal = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCal.sizePolicy().hasHeightForWidth())
        self.btnCal.setSizePolicy(sizePolicy)
        self.btnCal.setObjectName("btnCal")
        self.horizontalLayout_3.addWidget(self.btnCal)
        self.btnDisCon = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisCon.sizePolicy().hasHeightForWidth())
        self.btnDisCon.setSizePolicy(sizePolicy)
        self.btnDisCon.setCheckable(True)
        self.btnDisCon.setObjectName("btnDisCon")
        self.horizontalLayout_3.addWidget(self.btnDisCon)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gpb_Display.setTitle(_translate("MainWindow", "Movement Display"))
        self.gpb_Connection.setTitle(_translate("MainWindow", "Connection Status"))
        self.btnCon.setText(_translate("MainWindow", "Connect"))
        self.btnCal.setText(_translate("MainWindow", "Calibrate"))
        self.btnDisCon.setText(_translate("MainWindow", "Disconnect"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

